name: Fabric Test Runner

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: "Set up JDK 17"
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: "Run Fabric Tests"
        uses: SiskSjet/fabric-test-runner@v1
        with:
          minecraftVersion: 1.19.3
      - name: Extract current branch name
        shell: bash
        # bash pattern expansion to grab branch name without slashes
        run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
        id: ref
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v1
        with:
          name: entropy-artifacts-${{ steps.ref.outputs.branch }}
          path: build/libs/*[0-9].jar